name: Build project

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildForWindows32:
    name: Windows32 - 2020.2.3f1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ./Library
          key: Library-Cache-StandaloneWindows
          restore-keys: |
            Library-
      - uses: webbertakken/unity-builder@v2.0-alpha-6
        id: unityBuild
        with:
          projectPath: .
          unityVersion: 2020.2.3f1
          targetPlatform: StandaloneWindows
          versioning: Semantic
      - uses: actions/upload-artifact@v1
        with:
          name: Windows x32 ${{ steps.unityBuild.outputs.buildVersion }}
          path: build/StandaloneWindows
  buildForWindows64:
    name: Windows64 - 2020.2.3f1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ./Library
          key: Library-Cache-StandaloneWindows64
          restore-keys: |
            Library-Cache-
      - uses: webbertakken/unity-builder@v2.0-alpha-6
        id: unityBuild
        with:
          projectPath: '.'
          unityVersion: 2020.2.3f1
          targetPlatform: StandaloneWindows64
          versioning: Semantic
      - uses: actions/upload-artifact@v1
        with:
          name: Windows x64 ${{ steps.unityBuild.outputs.buildVersion }}
          path: build/StandaloneWindows64
  buildForOSX:
    name: OSX - 2020.2.3f1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ./Library
          key: Library-Cache-StandaloneOSX
          restore-keys: |
            Library-Cache-
      - uses: webbertakken/unity-builder@v2.0-alpha-6
        id: unityBuild
        with:
          projectPath: '.'
          unityVersion: 2020.2.3f1
          targetPlatform: StandaloneOSX
          versioning: Semantic
      - uses: actions/upload-artifact@v1
        with:
          name: OSX ${{ steps.unityBuild.outputs.buildVersion }}
          path: build/StandaloneOSX
  buildForLinux:
    name: Linux64 - 2020.2.3f1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ./Library
          key: Library-Cache-StandaloneLinux64
          restore-keys: |
            Library-Cache-
      - uses: webbertakken/unity-builder@v2.0-alpha-6
        id: unityBuild
        with:
          projectPath: '.'
          unityVersion: 2020.2.3f1
          targetPlatform: StandaloneLinux64
          versioning: Semantic
      - uses: actions/upload-artifact@v1
        with:
          name: Linux64 ${{ steps.unityBuild.outputs.buildVersion }}
          path: build/StandaloneLinux64
  buildForWebGL:
    name: WebGL - 2020.2.3f1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ./Library
          key: Library-Cache-WebGL
          restore-keys: |
            Library-Cache-
      - uses: webbertakken/unity-builder@v2.0-alpha-6
        id: unityBuild
        with:
          projectPath: '.'
          unityVersion: 2020.2.3f1
          targetPlatform: WebGL
          versioning: Semantic
      - uses: actions/upload-artifact@v1
        with:
          name: WebGL ${{ steps.unityBuild.outputs.buildVersion }}
          path: build/WebGL
